/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var __publicField = (obj, key, value) => __defNormalProp(obj, typeof key !== "symbol" ? key + "" : key, value);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => JustAudioPlayerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

// src/mediaController.ts
var MEDIA_EVENTS = [
  "play",
  "playing",
  "pause",
  "timeupdate",
  "durationchange",
  "loadedmetadata",
  "seeking",
  "seeked",
  "ended",
  "emptied",
  "abort"
];
function areStatesEqual(left, right) {
  return left.visible === right.visible && left.isPlaying === right.isPlaying && left.currentTime === right.currentTime && left.duration === right.duration && left.progress === right.progress && left.canSeek === right.canSeek && left.currentLabel === right.currentLabel && left.durationLabel === right.durationLabel;
}
function formatMediaTime(value) {
  if (!Number.isFinite(value) || value < 0) {
    return "0:00";
  }
  const totalSeconds = Math.floor(value);
  const seconds = totalSeconds % 60;
  const minutes = Math.floor(totalSeconds / 60) % 60;
  const hours = Math.floor(totalSeconds / 3600);
  if (hours > 0) {
    return `${hours}:${String(minutes).padStart(2, "0")}:${String(seconds).padStart(2, "0")}`;
  }
  return `${minutes}:${String(seconds).padStart(2, "0")}`;
}
function createDefaultScheduler() {
  if (typeof window !== "undefined" && typeof window.requestAnimationFrame === "function") {
    return {
      request: (callback) => window.requestAnimationFrame(callback),
      cancel: (id) => window.cancelAnimationFrame(id)
    };
  }
  const timeoutHandles = /* @__PURE__ */ new Map();
  let nextId = 1;
  return {
    request: (callback) => {
      const id = nextId;
      nextId += 1;
      const handle = globalThis.setTimeout(() => {
        timeoutHandles.delete(id);
        callback(Date.now());
      }, 100);
      timeoutHandles.set(id, handle);
      return id;
    },
    cancel: (id) => {
      const handle = timeoutHandles.get(id);
      if (handle) {
        globalThis.clearTimeout(handle);
        timeoutHandles.delete(id);
      }
    }
  };
}
function clampProgress(progress) {
  if (!Number.isFinite(progress)) {
    return 0;
  }
  return Math.min(1, Math.max(0, progress));
}
function getSafeDuration(media) {
  if (!media || !Number.isFinite(media.duration) || media.duration <= 0) {
    return 0;
  }
  return media.duration;
}
function getSafeCurrentTime(media) {
  if (!media || !Number.isFinite(media.currentTime) || media.currentTime < 0) {
    return 0;
  }
  return media.currentTime;
}
function shouldClearDetachedMedia(media) {
  return media.paused || media.ended;
}
function copyMediaPlaybackState(source, target) {
  target.src = source.src;
  target.innerHTML = source.innerHTML;
  target.currentTime = source.currentTime;
  target.muted = source.muted;
  target.playbackRate = source.playbackRate;
}
var JustAudioPlayerController = class {
  constructor(onStateChange = () => void 0, scheduler = createDefaultScheduler()) {
    __publicField(this, "onStateChange", onStateChange);
    __publicField(this, "scheduler", scheduler);
    __publicField(this, "media", null);
    __publicField(this, "visible", false);
    __publicField(this, "state", this.readState());
    __publicField(this, "frameId", null);
    __publicField(this, "handleMediaEvent", (event) => this.onMediaEvent(event.type));
    __publicField(this, "handleFrame", () => {
      this.frameId = null;
      this.publish();
      this.updateFrameLoop();
    });
  }
  setActiveMedia(media, reveal = true) {
    var _a;
    if (this.media !== media) {
      (_a = this.media) == null ? void 0 : _a.pause();
      this.unbindActiveMedia();
      this.media = media;
      for (const eventName of MEDIA_EVENTS) {
        media.addEventListener(eventName, this.handleMediaEvent);
      }
    }
    if (reveal) {
      this.visible = true;
    }
    this.publish();
    this.updateFrameLoop();
  }
  clearMedia(media) {
    if (media && this.media !== media) {
      return;
    }
    this.unbindActiveMedia();
    this.media = null;
    this.visible = false;
    this.publish();
  }
  isActiveMedia(media) {
    return this.media === media;
  }
  async togglePlayback() {
    if (!this.media) {
      return false;
    }
    if (this.media.paused || this.media.ended) {
      await this.media.play();
    } else {
      this.media.pause();
    }
    this.publish();
    this.updateFrameLoop();
    return true;
  }
  seekToProgress(progress) {
    if (!this.media) {
      return false;
    }
    const duration = getSafeDuration(this.media);
    if (duration === 0) {
      return false;
    }
    this.media.currentTime = duration * clampProgress(progress);
    this.publish();
    return true;
  }
  getState() {
    return { ...this.state };
  }
  destroy() {
    this.stopFrameLoop();
    this.unbindActiveMedia();
  }
  onMediaEvent(eventName) {
    if (eventName === "play" || eventName === "playing") {
      this.visible = true;
    }
    this.publish();
    this.updateFrameLoop();
  }
  readState() {
    const duration = getSafeDuration(this.media);
    const currentTime = Math.min(getSafeCurrentTime(this.media), duration || Number.POSITIVE_INFINITY);
    const canSeek = duration > 0;
    const progress = canSeek ? clampProgress(currentTime / duration) : 0;
    const isPlaying = Boolean(this.media && !this.media.paused && !this.media.ended);
    return {
      visible: this.visible,
      isPlaying,
      currentTime,
      duration,
      progress,
      canSeek,
      currentLabel: formatMediaTime(currentTime),
      durationLabel: formatMediaTime(duration)
    };
  }
  publish() {
    const nextState = this.readState();
    if (areStatesEqual(this.state, nextState)) {
      return;
    }
    this.state = nextState;
    this.onStateChange(this.getState());
  }
  updateFrameLoop() {
    const shouldRun = Boolean(this.media && !this.media.paused && !this.media.ended);
    if (shouldRun && this.frameId === null) {
      this.frameId = this.scheduler.request(this.handleFrame);
    }
    if (!shouldRun) {
      this.stopFrameLoop();
    }
  }
  stopFrameLoop() {
    if (this.frameId !== null) {
      this.scheduler.cancel(this.frameId);
      this.frameId = null;
    }
  }
  unbindActiveMedia() {
    if (!this.media) {
      return;
    }
    for (const eventName of MEDIA_EVENTS) {
      this.media.removeEventListener(eventName, this.handleMediaEvent);
    }
  }
};

// src/main.ts
var DEFAULT_SETTINGS = {
  width: 360,
  corner: "bottom-right"
};
var CORNER_OPTIONS = {
  "bottom-right": "Bottom right",
  "bottom-left": "Bottom left",
  "top-right": "Top right",
  "top-left": "Top left"
};
var MIN_WIDTH = 240;
var MAX_WIDTH = 720;
var TIMELINE_STEPS = 1e3;
function nodeContainsAudio(node) {
  if (!(node instanceof Element)) {
    return false;
  }
  return node.matches("audio") || node.querySelector("audio") !== null;
}
function mutationsMayAffectAudio(mutations) {
  return mutations.some((mutation) => {
    for (const node of Array.from(mutation.addedNodes)) {
      if (nodeContainsAudio(node)) {
        return true;
      }
    }
    for (const node of Array.from(mutation.removedNodes)) {
      if (nodeContainsAudio(node)) {
        return true;
      }
    }
    return false;
  });
}
function clampWidth(width) {
  if (!Number.isFinite(width)) {
    return DEFAULT_SETTINGS.width;
  }
  return Math.min(MAX_WIDTH, Math.max(MIN_WIDTH, Math.round(width)));
}
var JustAudioPlayerPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    __publicField(this, "settings", { ...DEFAULT_SETTINGS });
    __publicField(this, "playerEl", null);
    __publicField(this, "playButtonEl", null);
    __publicField(this, "currentTimeEl", null);
    __publicField(this, "durationEl", null);
    __publicField(this, "timelineEl", null);
    __publicField(this, "observer", null);
    __publicField(this, "detachedMediaEl", null);
    __publicField(this, "trackedMedia", /* @__PURE__ */ new Map());
    __publicField(this, "controller", new JustAudioPlayerController((state) => this.renderState(state)));
  }
  async onload() {
    await this.loadSettings();
    this.createPlayer();
    this.addSettingTab(new JustAudioPlayerSettingTab(this.app, this));
    this.startTrackingAudioElements();
  }
  onunload() {
    var _a, _b;
    this.stopTrackingAudioElements();
    this.controller.destroy();
    (_a = this.detachedMediaEl) == null ? void 0 : _a.remove();
    this.detachedMediaEl = null;
    (_b = this.playerEl) == null ? void 0 : _b.remove();
    this.playerEl = null;
  }
  async loadSettings() {
    var _a;
    const loaded = await this.loadData();
    this.settings = {
      ...DEFAULT_SETTINGS,
      ...loaded,
      width: clampWidth((_a = loaded == null ? void 0 : loaded.width) != null ? _a : DEFAULT_SETTINGS.width),
      corner: this.normalizeCorner(loaded == null ? void 0 : loaded.corner)
    };
  }
  async saveSettings() {
    this.settings.width = clampWidth(this.settings.width);
    this.settings.corner = this.normalizeCorner(this.settings.corner);
    await this.saveData(this.settings);
    this.applyPlayerSettings();
  }
  normalizeCorner(value) {
    if (typeof value === "string" && value in CORNER_OPTIONS) {
      return value;
    }
    return DEFAULT_SETTINGS.corner;
  }
  createPlayer() {
    const playerEl = document.createElement("div");
    playerEl.className = "just-audio-player is-hidden";
    playerEl.setAttribute("role", "region");
    playerEl.setAttribute("aria-label", "Active audio player");
    const playButtonEl = document.createElement("button");
    playButtonEl.className = "just-audio-player__button";
    playButtonEl.type = "button";
    playButtonEl.addEventListener("click", () => {
      void this.controller.togglePlayback().catch((error) => {
        console.error("Just Audio Player could not toggle playback", error);
      });
    });
    playerEl.appendChild(playButtonEl);
    const currentTimeEl = document.createElement("span");
    currentTimeEl.className = "just-audio-player__time";
    currentTimeEl.textContent = "0:00";
    playerEl.appendChild(currentTimeEl);
    const timelineEl = document.createElement("input");
    timelineEl.className = "just-audio-player__timeline";
    timelineEl.type = "range";
    timelineEl.min = "0";
    timelineEl.max = String(TIMELINE_STEPS);
    timelineEl.step = "1";
    timelineEl.value = "0";
    timelineEl.setAttribute("aria-label", "Audio timeline");
    timelineEl.addEventListener("input", () => {
      this.controller.seekToProgress(Number(timelineEl.value) / TIMELINE_STEPS);
    });
    playerEl.appendChild(timelineEl);
    const durationEl = document.createElement("span");
    durationEl.className = "just-audio-player__time";
    durationEl.textContent = "0:00";
    playerEl.appendChild(durationEl);
    document.body.appendChild(playerEl);
    this.playerEl = playerEl;
    this.playButtonEl = playButtonEl;
    this.currentTimeEl = currentTimeEl;
    this.durationEl = durationEl;
    this.timelineEl = timelineEl;
    this.applyPlayerSettings();
    this.renderState(this.controller.getState());
  }
  applyPlayerSettings() {
    if (!this.playerEl) {
      return;
    }
    for (const corner of Object.keys(CORNER_OPTIONS)) {
      this.playerEl.classList.toggle(`is-${corner}`, corner === this.settings.corner);
    }
    this.playerEl.style.setProperty("--just-audio-player-width", `${clampWidth(this.settings.width)}px`);
  }
  renderState(state) {
    if (!this.playerEl || !this.playButtonEl || !this.currentTimeEl || !this.durationEl || !this.timelineEl) {
      return;
    }
    this.playerEl.classList.toggle("is-hidden", !state.visible);
    this.playButtonEl.replaceChildren();
    (0, import_obsidian.setIcon)(this.playButtonEl, state.isPlaying ? "pause" : "play");
    this.playButtonEl.setAttribute("aria-label", state.isPlaying ? "Pause audio" : "Play audio");
    this.playButtonEl.setAttribute("title", state.isPlaying ? "Pause" : "Play");
    this.currentTimeEl.textContent = state.currentLabel;
    this.durationEl.textContent = state.durationLabel;
    this.timelineEl.disabled = !state.canSeek;
    this.timelineEl.value = String(Math.round(state.progress * TIMELINE_STEPS));
    this.timelineEl.setAttribute("aria-valuetext", `${state.currentLabel} of ${state.durationLabel}`);
  }
  startTrackingAudioElements() {
    this.scanForAudioElements();
    this.registerEvent(this.app.workspace.on("layout-change", () => this.scanForAudioElements()));
    this.registerEvent(this.app.workspace.on("active-leaf-change", () => this.scanForAudioElements()));
    this.observer = new MutationObserver((mutations) => {
      if (!mutationsMayAffectAudio(mutations)) {
        return;
      }
      this.scanForAudioElements();
      this.removeDetachedAudioElements();
    });
    this.observer.observe(document.body, {
      childList: true,
      subtree: true
    });
    this.register(() => this.stopTrackingAudioElements());
  }
  stopTrackingAudioElements() {
    var _a;
    (_a = this.observer) == null ? void 0 : _a.disconnect();
    this.observer = null;
    for (const cleanup of this.trackedMedia.values()) {
      cleanup();
    }
    this.trackedMedia.clear();
  }
  scanForAudioElements() {
    for (const media of Array.from(document.querySelectorAll("audio"))) {
      this.trackAudioElement(media);
      if (!media.paused && !media.ended) {
        this.controller.setActiveMedia(media, true);
      }
    }
    this.removeDetachedAudioElements();
  }
  trackAudioElement(media) {
    if (this.trackedMedia.has(media)) {
      return;
    }
    const activate = () => this.controller.setActiveMedia(media, true);
    media.addEventListener("play", activate);
    media.addEventListener("playing", activate);
    this.trackedMedia.set(media, () => {
      media.removeEventListener("play", activate);
      media.removeEventListener("playing", activate);
    });
  }
  removeDetachedAudioElements() {
    for (const [media, cleanup] of this.trackedMedia.entries()) {
      if (media.isConnected) {
        continue;
      }
      cleanup();
      this.trackedMedia.delete(media);
      if (shouldClearDetachedMedia(media)) {
        this.controller.clearMedia(media);
      } else if (this.controller.isActiveMedia(media)) {
        void this.keepDetachedPlaybackAlive(media).catch((error) => {
          console.error("Just Audio Player could not continue detached playback", error);
        });
      }
    }
  }
  async keepDetachedPlaybackAlive(source) {
    const detachedMediaEl = this.getDetachedMediaElement();
    copyMediaPlaybackState(source, detachedMediaEl);
    this.controller.setActiveMedia(detachedMediaEl, true);
    await detachedMediaEl.play();
    source.pause();
  }
  getDetachedMediaElement() {
    if (this.detachedMediaEl) {
      return this.detachedMediaEl;
    }
    const media = document.createElement("audio");
    media.preload = "auto";
    media.className = "just-audio-player__detached-media";
    document.body.appendChild(media);
    this.detachedMediaEl = media;
    return media;
  }
};
var JustAudioPlayerSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    __publicField(this, "plugin", plugin);
  }
  display() {
    const { containerEl } = this;
    containerEl.replaceChildren();
    new import_obsidian.Setting(containerEl).setName("Player width").setDesc("Width of the floating player in pixels.").addSlider((slider) => {
      slider.setLimits(MIN_WIDTH, MAX_WIDTH, 10).setValue(this.plugin.settings.width).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.width = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Player corner").setDesc("Application corner used to anchor the player.").addDropdown((dropdown) => {
      dropdown.addOptions(CORNER_OPTIONS);
      dropdown.setValue(this.plugin.settings.corner);
      dropdown.onChange(async (value) => {
        this.plugin.settings.corner = value;
        await this.plugin.saveSettings();
      });
    });
  }
};
